### PR TITLE
fix bug where wrong value in config file was referenced

### LINKED ISSUE #40: Port Events Min Points Bug
See this slack thread: https://globalfishingwatch.slack.com/archives/C67TJ42BZ/p1548340848001200

In particular: 

```I think I’ve found the underlying problem.  `min_required_positions` used here https://github.com/GlobalFishingWatch/anchorages_pipeline/blob/master/pipe_anchorages/port_events_pipeline.py#L62 is supposed to be `min_port_events_positions`. Those values are 200 and 2 respectively. What that means is that currently and day with less than 200 positions gets dropped from the output of port events. In this case, the vessel in question has less than 200 points on the 12th and 13th, so it’s exit gets dropped.```

### PR DESCRIPTION
**Pull request by bitsofbits**
Closes #40 

* Fix use of incorrect value from config file. Was using `min_required_positions` instead of
  the correct `min_port_events_positions`

### CODE REVIEW

**Comment by bitsofbits** [comment]
This query shows the problem: ```
#StandardSql
SELECT a.*, FINAL_NAME FROM `world-fishing-827.pipe_production_b.port_events_201901*` a
join `gfw_raw.anchorage_naming_20171026`
on anchor_id = anchorage_id
WHERE VESSEL_ID in (
'e74a8b019-98a3-4a87-9caf-2595a097f7cd', '0afe10088-8ead-1a1a-b54d-2cc8af49430c'
) AND FINAL_NAME = 'MEJILLONES,CHL'
order by timestamp
LIMIT 1000
```
Returning 
<img width="272" alt="screen shot 2019-01-25 at 4 17 28 pm" src="https://user-images.githubusercontent.com/9038617/51777992-e0dc8680-20bc-11e9-83dc-8b794cbb3c72.png">

**Comment by bitsofbits** [comment]
After the fix, using
```
#StandardSql
-- SELECT a.*, FINAL_NAME FROM `world-fishing-827.pipe_production_b.port_events_201901*` a
SELECT a.*, FINAL_NAME FROM `machine_learning_dev_ttl_120d.testporteventpr_*` a
join `gfw_raw.anchorage_naming_20171026`
on anchor_id = anchorage_id
WHERE VESSEL_ID in (
'e74a8b019-98a3-4a87-9caf-2595a097f7cd', '0afe10088-8ead-1a1a-b54d-2cc8af49430c'
) AND FINAL_NAME = 'MEJILLONES,CHL'
order by timestamp
LIMIT 1000
```

The `PORT_EXIT` is correctly generated.

screen shot 2019-01-25 at 4 20 30 pm

**Comment by bitsofbits** [comment]
@enriquetuya : the mystery is that the code in master doesn't appear to be set up to run with the config file you posted. The fields are wrong. Also the output of anchorages appear to be different. Is the anchorages pipeline using older code?

**Comment by bitsofbits** [comment]
Config from Slack that I mentioned so it's easy to find:
```
{
  "anchorage_table": "gfw_raw.anchorage_naming_20171026", 
  "dag_install_path": "/usr/local/airflow/dags/github-globalfishingwatch-anchorages_pipeline", 
  "dataflow_runner": "DataflowRunner", 
  "docker_image": "gcr.io/world-fishing-827/github-globalfishingwatch-anchorages_pipeline:v0.2.1", 
  "docker_run": "{{ var.value.DOCKER_RUN }}", 
  "events_dataset": "{{ var.value.EVENTS_DATASET }}", 
  "events_table": "port_events", 
  "pipeline_bucket": "{{ var.value.PIPELINE_BUCKET }}", 
  "pipeline_dataset": "{{ var.value.PIPELINE_DATASET }}", 
  "port_events_table": "port_events_", 
  "port_visits_start_padding": "365", 
  "port_visits_table": "port_visits_", 
  "project_id": "{{ var.value.PROJECT_ID }}", 
  "source_dataset": "{{ var.value.PIPELINE_DATASET }}", 
  "source_table": "position_messages_", 
  "temp_bucket": "{{ var.value.TEMP_BUCKET }}"
}
```

**Comment by enriquetuya** [comment]
@bitsofbits the configuration I sent is for the version `v0.2.1` that is running in `pipe-production-b`. So it is possible that the configuration doesn't match. I think that we are in `v0.3.2` in master now.

**Comment by bitsofbits** [comment]
@enriquetuya , if I use the updated table name you gave me then this runs fine without me messing with query.  All that needs to be changed is fixing `min_port_events_positions`. This still fixes the bug Hannah found as well. The test case: 

```
    docker-compose run port_events \
        --job_name testporteventpr \
        --input_table pipe_production_b.position_messages_ \
        --anchorage_table gfw_research.named_anchorages_v20180803_13b \
        --start_date 2019-01-11 \
        --end_date 2019-01-13 \
        --output_table machine_learning_dev_ttl_120d.testporteventpr_ \
        --project world-fishing-827 \
        --max_num_workers 100 \
        --requirements_file requirements.txt \
        --project world-fishing-827 \
        --staging_location gs://machine-learning-dev-ttl-30d/anchorages/portevents/output/staging \
        --temp_location gs://machine-learning-dev-ttl-30d/anchorages/temp \
        --setup_file ./setup.py \
        --runner DataflowRunner \
        --disk_size_gb 100
```

**Pull request merged**
